version: "3.0"
services:
  ms-frontend:
    build: frontend
    ports:
      - "3000:3000"
    networks:
      - backend
    environment:
    - PRODUCTS_SERVICE=host.docker.internal
    - SHOPPING_CART_SERVICE=host.docker.internal
    volumes:
      - .:/app
  ms-products:
    build: /products
    ports:
      - "3001:3001"
    environment:
    - PRODUCTS_SERVICE=host.docker.internal
    - SHOPPING_CART_SERVICE=host.docker.internal
    networks:
      - frontend
    volumes:
      - .:/app
  ms-shopping-cart:
    build: /shopping-cart
    container_name: shopping-cart
    ports:
      - "3002:3002"
    environment:
    - PRODUCTS_SERVICE=host.docker.internal
    - SHOPPING_CART_SERVICE=host.docker.internal
    volumes:
      - .:/app
