version: "3.9"
services:
  web:
    build: services/frontend
    ports:
      - "5000:5000"
    networks:
      - frontend
      - backend
  reader:
    build: services/reader
    ports:
      - "3000:3001"
    networks:
      - frontend
  writer:
    build: services/writer
    ports:
      - "8080:8080"
    networks:
      - backend
  reids:
    image: "redis:alpine"

networks:
  backend:
